exports.smartContract = {
     "id": 1,
     "key": "356a192b7913b04c54574d18c28d46e6395428ab",
     "name": "Honey Trade",
     "description": "Manage Honey production and trade",
     "dateCreated": "2019-01-03T11:14:13.302Z",
     "lastUpdated": "2019-02-03T08:05:56.302Z",
     "actors" : [
       {
         "id" : 1,
         "key" : "356a192b7913b04c54574d18c28d46e6395428ab_Actor1",
         "name" : "Harvester",
         "description": "Collects the honey from harvesters",
       },
       {
         "id" : 2,
         "key" : "356a192b7913b04c54574d18c28d46e6395428ab_Actor2",
         "name" : "Wholesaler",
         "description": "Buys the honey from harvesters",
       },
       {
         "id" : 3,
         "key" : "356a192b7913b04c54574d18c28d46e6395428ab_Actor3",
         "name" : "Shipper",
         "description": "Ships the honey to the buyers",
       },
       {
         "id" : 4,
         "key" : "356a192b7913b04c54574d18c28d46e6395428ab_Actor4",
         "name" : "Buyer",
         "description": "Buys the honey from wholesalers",
       },
      ],
     "actions" : [
        {
         "id" : 1,
         "key" : "356a192b7913b04c54574d18c28d46e6395428ab_honey",
         "name" : "Harvest",
         "description" : "Honey is harvested and is available for sale",
         "events" : [
            {
             "name" : "Harvested",
             "properties" : [
                {
                    "name" : "sku",
                    "type" : "uint"
                },
                {
                  "name" : "upc",
                  "type" : "uint"
                }
             ]
            },
          ],
         "awardedPermissions" : [
            {
              "name" : "HARVESTER_OF_",
              "grantedTo" : "msg.sender",
            },
          ],
          "requiredRoles" : [
            {
              "name" : "HARVEST_ROLE",
              "grantedTo" : "msg.sender",
            },
          ],
         "properties" : [
            {
                "key" : "sku",
                "name" : "sku",
                "displayName" : "sku",
                "description" : "Stock Keeping Unit (SKU)",
                "type" : "uint",
                "isCounter" : true
            },
            {
              "key" : "upc",
              "name" : "upc",
              "displayName" : "upc",
              "description" : "Universal Product Code (UPC), generated by the Harvester, goes on the package, can be verified by the Buyer",
              "type" : "uint",
              "isUnique" : true
            },
            {
              "key" : "harvesterId",
              "name" : "harvesterId",
              "displayName" : "Harvester Id",
              "description" : "Metamask-Ethereum address of the Harvester",
              "type" : "address",
              "isSender" : true
            },
            {
              "key" : "originBeekeeperID",
              "name" : "originBeekeeperId",
              "displayName" : "Origin Beekeeper Id",
              "description" : "Metamask-Ethereum address of the BeeKeeper",
              "type" : "address"
            },
            {
              "key" : "originBeekeeperName",
              "name" : "originBeekeeperName",
              "displayName" : "Origin Beekeeper Name",
              "description" : "BeeKeeper Name",
              "type" : "string"
            },
            {
              "key" : "originFarmInformation",
              "name" : "originFarmInformation",
              "displayName" : "Origin Farm Information",
              "description" : "BeeKeeper Information",
              "type" : "string"
            },
            {
              "key" : "originFarmLatitude",
              "name" : "originFarmLatitude",
              "displayName" : "Origin Farm Latitude",
              "description" : "Farm Latitude",
              "type" : "string"
            },
            {
              "key" : "originFarmLongitude",
              "name" : "originFarmLongitude",
              "displayName" : "Origin Farm Longitude",
              "description" : "Farm Longitude",
              "type" : "string"
            },
            {
              "key" : "quantity",
              "name" : "quantity",
              "displayName" : "Quantity",
              "description" : "Quantity in milliliters",
              "type" : "uint"
            },
            {
              "key" : "productID",
              "name" : "productId",
              "displayName" : "Product Id",
              "description" : "Product ID potentially a combination of upc + sku",
              "type" : "uint"
            },
            {
              "key" : "productNotes",
              "name" : "productNotes",
              "displayName" : "Product Notes",
              "description" : "Product Notes",
              "type" : "string"
            },
            {
              "key" : "productPrice",
              "name" : "productPrice",
              "displayName" : "Product Price",
              "description" : "Product Price",
              "type" : "uint"
            },
            {
              "key" : "shipperID",
              "name" : "shipperId",
              "displayName" : "Shipper Id",
              "description" : "Metamask-Ethereum address of the Shipper",
              "type" : "address"
            },
            {
              "key" : "buyerID",
              "name" : "buyerId",
              "displayName" : "Buyer Id",
              "description" : "Metamask-Ethereum address of the Buyer",
              "type" : "address"
            },
          ]
       },
       {
         "id" : 1,
         "key" : "356a192b7913b04c54574d18c28d46e6395428ab_Action1",
         "name" : "Order",
         "description": "Buyer places order",
         "events" : [
           {
             "name" : "PlacedOrder",
             "properties" : [
              {
                "name" : "upc",
                "type" : "uint"
              }
             ]
           }
          ],
         "awardedPermissions" : [
            {
              "name" : "ORDER_OF_",
              "grantedTo" : "msg.sender",
            },
          ],

         "properties" : [
            {
                "key" : "orderId",
                "name" : "orderId",
                "displayName" : "Order Id",
                "description" : "",
                "type" : "uint",
                "isCounter" : true
            },
            {
              "key" : "buyerId",
              "name" : "buyerId",
              "displayName" : "Buyer Id",
              "description" : "",
              "type" : "address"
            },
            {
              "key" : "upc",
              "name" : "upc",
              "displayName" : "upc",
              "description" : "",
              "type" : "uint",
              "isUnique" : true
            },
            {
              "key" : "quantity",
              "name" : "quantity",
              "displayName" : "quantity",
              "description" : "",
              "type" : "uint"
            },
          ],
       },
       {
         "id" : 2,
         "key" : "356a192b7913b04c54574d18c28d46e6395428ab_Action2",
         "name" : "Quote",
         "description": "Harvester provides Quote",
         "events" : [
            {
             "name" : "MadeQuote",
             "properties" : [
                {
                    "name" : "orderId",
                    "type" : "uint"
                },
                {
                  "name" : "price",
                  "type" : "uint"
                }
             ]
            }
          ],
         "awardedPermissions" : [
            {
              "name" : "BUYER_OF_",
              "grantedTo" : "buyerId"
            },
          ],
          "awardedRoles" : [
            {
              "name" : "BUYER_ROLE_",
              "grantedTo" : "msg.sender",
            },
          ],
          "requiredRoles" : [
            {
              "name" : "HARVEST_ROLE",
              "grantedTo" : "msg.sender",
            },
          ],
          "rules" : [
            {
              "formulae":
              [
                {"value" : "shippingDownPayment"},
                {"value" : "<="},
                {"value" : "shippingCost"},
              ],
              "message" : "SHIPPINGDOWNPAYMENT > SHIPPINGCOST"
            }
          ],
          "properties" : [
            {
              "key" : "quoteId",
              "name" : "quoteId",
              "displayName" : "Quote Id",
              "description" : "",
              "type" : "uint",
              "isCounter" : true
            },
            {
              "key" : "orderId",
              "name" : "orderId",
              "displayName" : "Order Id",
              "description" : "",
              "type" : "uint",
              "isUnique" : true
            },
            {
              "key" : "upc",
              "name" : "upc",
              "displayName" : "upc",
              "description" : "",
              "type" : "uint"
            },
            {
              "key" : "price",
              "name" : "price",
              "displayName" : "Price",
              "description" : "",
              "type" : "uint"
            },
            {
              "key" : "shipperId",
              "name" : "shipperId",
              "displayName" : "Shipper Id",
              "description" : "",
              "type" : "address"
            },
            {
              "key" : "shippingCost",
              "name" : "shippingCost",
              "displayName" : "Shipping Cost",
              "description" : "",
              "type" : "uint"
            },
            {
              "key" : "shippingDownPayment",
              "name" : "shippingDownPayment",
              "displayName" : "Shipping Down Payment",
              "description" : "",
              "type" : "uint"
            },
            {
              "key" : "date",
              "name" : "date",
              "displayName" : "Date",
              "description" : "",
              "type" : "uint"
            },
            ],
        },
        {
          "id" : 3,
          "key" : "356a192b7913b04c54574d18c28d46e6395428ab_Action3",
          "name" : "Purchase",
          "description": "Buyer purchases honey",
          "events" : [
              {
                "name" : "Purchased",
                "properties" : [{"name" : "purchaseId", "type" : "uint"}],
              }
            ],
          "awardedPermissions" : [
            {
              "name" : "SHIPPER_OF_",
              "grantedTo" : "shipperId"
            },
          ],
          "requiredRoles" : [
            {
              "name" : "BUYER_ROLE_",
              "grantedTo" : "msg.sender"
            },
          ],
          "requiredPermissions" : [
            {
              "name" : "BUYER_OF_ROLE",
              "grantedTo" : "msg.sender"
            },
          ],
          "properties" : [
            {
                "key" : "purchaseId",
                "name" : "purchaseId",
                "displayName" : "Purchase Id",
                "description" : "",
                "type" : "uint",
                "isCounter" : true
            },
            {
                "key" : "quoteId",
                "name" : "quoteId",
                "displayName" : "Quote Id",
                "description" : "",
                "type" : "uint",
                "isUnique" : true
            },
            {
              "key" : "orderId",
              "name" : "orderId",
              "displayName" : "Order Id",
              "description" : "",
              "type" : "uint"
            },
            {
              "key" : "upc",
              "name" : "upc",
              "displayName" : "upc",
              "description" : "",
              "type" : "uint"
            },
            {
              "key" : "shipmentId",
              "name" : "shipmentId",
              "displayName" : "Shipment Id",
              "description" : "",
              "type" : "uint"
            },
            {
              "key" : "date",
              "name" : "date",
              "displayName" : "Date",
              "description" : "",
              "type" : "uint"
            },
          ],
       },
       {
         "id" : 3,
         "key" : "356a192b7913b04c54574d18c28d46e6395428ab_Action4",
         "name" : "Shipment",
         "description": "Shipper ships honey",
         "events" : [
            {
              "name" : "Shipped",
              "properties" : [{"name" : "shipmentId", "type" : "uint"}],
            },
          ],
         "awardedPermissions" : [
            {
              "name" : "RECIEVER_OF_",
              "grantedTo" : "buyerId"
            },
          ],
         "properties" : [
            {
              "key" : "shipmentId",
              "name" : "shipmentId",
              "displayName" : "Shipment Id",
              "description" : "",
              "type" : "uint",
              "isCounter" : true
            },
            {
              "key" : "shipper",
              "name" : "shipper",
              "displayName" : "Shipper",
              "description" : "",
              "type" : "address"
            },
            {
                "key" : "purchaseId",
                "name" : "purchaseId",
                "displayName" : "Purchase Id",
                "description" : "",
                "type" : "uint",
                "isUnique" : true
            },
            {
              "key" : "quoteId",
              "name" : "quoteId",
              "displayName" : "Quote Id",
              "description" : "",
              "type" : "uint"
            },
            {
              "key" : "orderId",
              "name" : "orderId",
              "displayName" : "Order Id",
              "description" : "",
              "type" : "uint"
            },
            {
              "key" : "upc",
              "name" : "upc",
              "displayName" : "upc",
              "description" : "",
              "type" : "uint"
            },
            {
              "key" : "date",
              "name" : "date",
              "displayName" : "Date",
              "description" : "",
              "type" : "uint"
            },
            {
              "key" : "delivered",
              "name" : "delivered",
              "displayName" : "Delivered",
              "description" : "",
              "type" : "bool"
            },
            {
              "key" : "dateDelivered",
              "name" : "dateDelivered",
              "displayName" : "Date Delivered",
              "description" : "",
              "type" : "uint"
            },
          ],
       },
       {
         "id" : 4,
         "key" : "356a192b7913b04c54574d18c28d46e6395428ab_Action5",
         "name" : "Delivery",
         "description": "Buyer recieves honey and pays",
         "events" : [
            {
              "name" : "Delivered",
              "properties" : [{"name" : "deliveryId", "type" : "uint"}],
            },
          ],
         "properties" : [
            {
              "key" : "deliveryId",
              "name" : "deliveryId",
              "displayName" : "Delivery Id",
              "description" : "",
              "type" : "uint",
              "isCounter" : true
            },
            {
              "key" : "shipmentId",
              "name" : "shipmentId",
              "displayName" : "Shipment Id",
              "description" : "",
              "type" : "uint",
              "isUnique" : true
            },
            {
                "key" : "purchaseId",
                "name" : "purchaseId",
                "displayName" : "Purchase Id",
                "description" : "",
                "type" : "uint"
            },
            {
              "key" : "quoteId",
              "name" : "quoteId",
              "displayName" : "Quote Id",
              "description" : "",
              "type" : "uint"
            },
            {
              "key" : "orderId",
              "name" : "orderId",
              "displayName" : "Order Id",
              "description" : "",
              "type" : "uint"
            },
            {
              "key" : "upc",
              "name" : "upc",
              "displayName" : "upc",
              "description" : "",
              "type" : "uint"
            },
            {
              "key" : "date",
              "name" : "date",
              "displayName" : "Date",
              "description" : "",
              "type" : "uint"
            },
          ],
       }
      ]
 };